### ISSUE TITLE
handle proper reporting when an async task fails

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-installer#79]
It currently just leaves the task without updates. But the logs show things like:

    [2016-02-25 16:05:37,893: INFO/Worker-2] COMMIT
    [2016-02-25 16:05:37,894: WARNING/Worker-2] "CEPH_ANSIBLE_PATH" environment variable is not defined
    [2016-02-25 16:05:37,894: INFO/Worker-2] Running command: /usr/local/bin/ansible-playbook -u ceph-installer /usr/share/ceph-ansible/site.yml.sample -i /var/folders/t8/smzdykh12h39f8r0vwv5vzf00000gn/T/47be0832-9bb4-42ed-8c66-c805e40e24f2_vp98g8 --extra-vars {"ceph_stable": true} --tags package-install
    [2016-02-25 16:05:37,905: ERROR/MainProcess] Task ceph_installer.tasks.call_ansible[a95437e8-b0e7-43fd-8ea1-c2a8d4cd93e0] raised unexpected: OSError(2, 'No such file or directory')
    Traceback (most recent call last):
      File "/Users/alfredo/.virtualenvs/ceph-installer/lib/python2.7/site-packages/celery-3.1.20-py2.7.egg/celery/app/trace.py", line 240, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/Users/alfredo/.virtualenvs/ceph-installer/lib/python2.7/site-packages/celery-3.1.20-py2.7.egg/celery/app/trace.py", line 438, in __protected_call__
        return self.run(*args, **kwargs)
      File "/Users/alfredo/python/upstream/ceph-installer/ceph_installer/tasks.py", line 41, in call_ansible
        out, err, exit_code = process.run(command, **kwargs)
      File "/Users/alfredo/python/upstream/ceph-installer/ceph_installer/process.py", line 61, in run
        **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory: '/usr/share/ceph-ansible'

**Comment by alfredodeza** [comment]
fixed with pull request #89
